### ISSUE TITLE
isolate from svn client

### ISSUE THREAD

**Issue by albfan** [AlternateComputingSolutions/jsvn#1]
On many OS, svn is not avaliable as client (e.g windows OS) but exists java implementations fully capable to mimic a complete svn client 

http://svnkit.com/download.php

Allow jsvn to be configurable about svn client

**Comment by albfan** [comment]
Seeing work done, seems at least to config files should be generated. One for data like executable, encoding,etc... and one for last accesed working copies,  or info related with work done

**Comment by golpira** [comment]
There probably is good reason for JSVN to support interacting with a repository using both a native client and using the svn-kit library.

Currently, repository access is accomplished via the Command class and its subclasses.  A better abstraction for the command classes could be created.  There could be alternate implementations of those interfaces (one using native SVN client, one using svn-kit).  An abstract factory pattern could be used to create the required command instance for a given client.

Doing something like this, JSVN could be changed to support the new abstraction using the native client implementation.  That could be verified for correct functionality.  As a separate task, the command factory could be updated (either at the same time or later) to provide command implementations that use svn-kit.

From a quick look at svn-kit, it may be easiest to have the "pure java"-backed command implementations use SVN*Client objects created by SVNClientManager.

As you point out, config settings should be maintained to keep track of which repository interface JSVN is using.

Thoughts?

**Comment by albfan** [comment]
Totally agree. By know lets rework the wrapper around native client and prepare a factory to ease transition to a java implementation.
