### ISSUE TITLE
recover testsuite from original repo

### ISSUE THREAD

**Issue by albfan** [AlternateComputingSolutions/jsvn#6]
Do this really ever exists?

https://github.com/AlternateComputingSolutions/jsvn/blob/master/build.xml#L28

Any work done would be appreciated. Anyway if not would be easy to recreate

**Comment by golpira** [comment]
I wouldn't worry too much about that missing class.  As mentioned in issue #5 , I think migrating the build to either Maven or Gradle will make the build process more manage.  Once that is done, adding unit tests as part of the build would trivial.  I would advise against spending too much time fixing up the Ant build script and instead switch to a better build tool.

**Comment by albfan** [comment]
I'm asking for it to see if there's anything usable there. I'm agree that can be easily create. Let'z do from scratch then.
